on:
  release:
    types: [created]
name: upload asset
jobs:
  pack:
    name: pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install node@12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: build
        run: |
          yarn
          yarn workspace ui run build
          tsc -p ./packages/plugin/tsconfig.json
          cp -r ./packages/plugin/ ./dist/plugin/
      - name: pack
        uses: mohuishou/utools/.github/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dir: ./dist
          filename: utools-autodelete-vue
          tag_name: $ {{ github.ref }}
          upload_url: ${{ github.event.release.upload_url }}
